### ISSUE TITLE
echo -e flag leaking into output

### ISSUE THREAD

**Issue by sevko** [rhysd/ghci-color#3]
The `-e` flag in the [`echo -e` commands](https://github.com/rhysd/ghci-color/blob/master/ghci-color#L3,L9) appears to be leaking into the output, like so:

```
$ ghci-color
GHCi, version 7.6.3: http:-e /-e -e /-e www.haskell.org-e /-e ghc-e /-e   :? for help
Loading package ghc-prim ... linking ... -e done.-e 
Loading package integer-gmp ... linking ... -e done.-e 
Loading package base ... linking ... -e done.-e 
Prelude> 
```

With the flag removed, I still see colored output but no trailing `-e`s:

```
$ ghci-color                             
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> 
```

Note that when I enter the following directly in my shell, `hello, world` is colored (even with the `-e` flag omitted) but no `-e` is visible:

```
$ echo -e '\033[92mhello, world'
hello, world
```

A very minor issue (that I've fixed on my end anyway), but perhaps you'll know the reason for it off the top of your head.

**Comment by sevko** [comment]
I've identified the issue. `zsh` (my personal shell) and `bash` both omit the `-e` from the output, but `dash` (which the `#!/usr/bin/env sh` shebang invokes) doesn't, since its `echo` [doesn't recognize the `-e` parameter](http://stackoverflow.com/questions/4435853/echo-outputs-e-parameter-in-bash-scripts-how-can-i-prevent-this). If there's no concrete using for using dash, can you change the shebang to `#!/usr/bin/env bash`? See:

```
zsh % sh  
$ echo -e '\033[92m some nonsense'
-e  some nonsense
```

**Comment by michaelochurch** [comment]
I had the same problem. @sevko Thanks for the fix.

**Comment by rhysd** [comment]
Ah, nice catch!
I've not noticed because I only use `bash` or `zsh`.  I tried fixing.  Is it working well?

**Comment by sevko** [comment]
Yep! Thanks.

**Comment by rhysd** [comment]
:dog: :tada:
