### ISSUE TITLE
I use stack, how do I use this script?

### ISSUE THREAD

**Issue by AurevoirXavier** [rhysd/ghci-color#5]
I need to type 'stack ghci' to enter REPL.

**Comment by rhysd** [comment]
Can `stack ghc --intaractive` also start ghci?

**Comment by AurevoirXavier** [comment]
Invalid option `--interactive'

**Comment by rhysd** [comment]
I don't know stack tool, but I guess replacing copy `ghci-color` to your `bin` directory and modifying https://github.com/rhysd/ghci-color/blob/master/ghci-color#L25 as following would work.

```
exec stack ghci ${1+"$@"} 2>&1 |\
```

**Comment by AurevoirXavier** [comment]
Thanks.
